disable release finish merge back develop

diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -218,9 +218,9 @@ cmd_finish() {
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
+	#if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
+	#	require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	#fi
 
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
@@ -258,23 +258,23 @@ cmd_finish() {
 	# try to merge into develop
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into develop was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-		git_do checkout "$DEVELOP_BRANCH" || \
-		  die "Could not check out $DEVELOP_BRANCH."
+	#if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
+		#git_do checkout "$DEVELOP_BRANCH" || \
+		  #die "Could not check out $DEVELOP_BRANCH."
 
 		# TODO: Actually, accounting for 'git describe' pays, so we should
 		# ideally git merge --no-ff $tagname here, instead!
-		if noflag squash; then
-			git_do merge --no-ff "$BRANCH" || \
-				die "There were merge conflicts."
+		#if noflag squash; then
+			#git_do merge --no-ff "$BRANCH" || \
+				#die "There were merge conflicts."
 				# TODO: What do we do now?
-		else
-			git_do merge --squash "$BRANCH" || \
-				die "There were merge conflicts."
+		#else
+			#git_do merge --squash "$BRANCH" || \
+				#die "There were merge conflicts."
 				# TODO: What do we do now?
-			git_do commit
-		fi
-	fi
+			#git_do commit
+		#fi
+	#fi
 
 	# delete branch
 	if noflag keep; then
@@ -285,8 +285,8 @@ cmd_finish() {
 	fi
 
 	if flag push; then
-		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+		#git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
+			#die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
 		if noflag notag; then
@@ -303,8 +303,8 @@ cmd_finish() {
 	echo "- Release branch has been merged into '$MASTER_BRANCH'"
 	if noflag notag; then
 		echo "- The release was tagged '$tagname'"
-	fi
-	echo "- Release branch has been back-merged into '$DEVELOP_BRANCH'"
+	#fi
+	#echo "- Release branch has been back-merged into '$DEVELOP_BRANCH'"
 	if flag keep; then
 		echo "- Release branch '$BRANCH' is still available"
 	else
